---
title: "Grade distributions - Spring 2025"
format: html
---

```{r}
#| label: setup
#| include: false
library("here")
library("dplyr")
library("tidyr")
library("purrr")
library("fs")
library("readxl")
library("stringr")
library("janitor")
library("glue")
library("ggplot2")
library("forcats")

dat <- read_xlsx(here("data", "Spanish Spring 25 Grades.xlsx"), skip = 1) |> 
  clean_names() |> 
  select(
    subj = subj_cd, 
    course_n = course_no, 
    section_n = section_no, 
    a:b, 
    b_plus = b_2, 
    c, 
    c_plus = c_2, 
    d:z
  ) |>
  filter(!is.na(subj)) |> 
  mutate(across(everything(), as.numeric)) |> 
  mutate(across(everything(), \(x) replace_na(x, replace = 0))) |> 
  pivot_longer(
    cols = a:z, 
    names_to = "grade", 
    values_to = "n"
  ) |>
  mutate(
    grade = case_when(
      grade == "b_plus" ~ "B+", 
      grade == "c_plus" ~ "C+", 
      TRUE ~ grade
    ), 
    grade = str_to_title(grade), 
    grade = fct_relevel(
      grade, "A", "B+", "B", "C+", "C", "D", "F"
    )
  ) 

  
```


```{r}
#| label: fig-all-grades
total_grades <- sum(dat$n)

dat |> 
  group_by(grade) |> 
  summarize(n = sum(n)) |> 
  filter(grade %in% c("A", "B", "B+", "C", "C+", "D", "F")) |> 
  ggplot() + 
  aes(x = n, y = grade, label = n) + 
  geom_segment(aes(x = 0, xend = n, y = grade), linewidth = 4, color = "#cc0033") + 
  geom_point(pch = 21, size = 9, fill = "white") + 
  geom_text(size = 3) + 
  scale_y_discrete(limits = rev) + 
  labs(
    title = "Distribution of grades", 
    subtitle = glue("Spring 2025 (n = {total_grades})"), 
    y = "Grade", 
    x = "Total"
  ) + 
  ds4ling::ds4ling_bw_theme() + 
  theme(axis.text.y = element_text(hjust = 0))
```

